
# Start a lightweight python brain
FROM python:3.11-slim
# set working directory inside the container
WORKDIR /app
# copy requirements and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# copy all of your local code into the container
COPY . .
# install  custom project package
RUN pip install -e .
# expose the fastapi port
EXPOSE 8000
# boot up Uvicorn serve
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
